version: "3.8"
services:
  restapi-jbdc-container:
    image: ghcr.io/rubyfeller/s3-ip-restapi:master
    ports:
      - "8080:8080"
    networks:
      - restapi-mysql
    depends_on:
      - docker-mysql

  docker-mysql:
    image: mysql:8.0.29
    networks:
      - restapi-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database

networks:
  restapi-mysql: